spring.application.name=Cholo Sikhai Ai
server.port=8081
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.google.genai.api-key=${AI_API_KEY}
spring.ai.google.genai.project-id=${AI_PROJECT_ID}
spring.ai.google.genai.embedding.api-key=${AI_API_KEY}
spring.ai.google.genai.embedding.project-id=${AI_PROJECT_ID}
#spring.ai.google.genai.chat.model=gemini-1.5-flash
spring.ai.google.genai.chat.temperature=0.7
spring.ai.google.genai.embedding.options.model=text-embedding-004
spring.ai.google.genai.embedding.options.dimensions=768

spring.datasource.url=${VECTOR_DB_URL}
spring.ai.vectorstore.pgvector.initialize-schema=true
#spring.ai.vectorstore.pgvector.remove-existing-vector-store-table=true
spring.ai.vectorstore.pgvector.dimensions=3072
spring.ai.vectorstore.pgvector.index-type=NONE
